language: csharp
mono: none
sudo: false
dotnet: 3.1
dist: bionic


script:
  - dotnet build -c Release
  - dotnet test  -c Release --no-build
  - dotnet pack  -c Release --no-build -p:NoWarn=NU5105


deploy:


  - on:
      branch: master
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
    skip_cleanup: true


  - on:
      branch: develop
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://www.myget.org/F/nettopologysuite/api/v3/index.json -k $MYGET_API_KEY --skip-duplicate
    skip_cleanup: true

env:
  global:
  - secure: IopD8S89evOEPNsyb5+9iU/AgCUF5xMWEKzzInQwpAxr2KvjCQBQISC3n7Glj31DMmFjW7J/KZir5uKBgGkWvaJ6WPlsfXvXrEl8TpUN/uXzd4w3hkmcrunRVnnufm550PH1oY83c97vtxDPECIW6RyZOqkqjfAYesaBE2/gHShZGU/Anol/vwzY6Z56vge3nqpLJpISZ6Fxvr8Ion20tiLzctIWM/SrVM1uvxaVxeeDIVE93xEFvmJN9H1vAhuIbvpylGpfqjzHveSVTdtinRe384Oa2VgXll7AzLzTGzB+Ykyg1fiFTprO2dVfaprHtO98ifnp2xotiglI94EHe/x6HofppaQKMMU7cTNBIpTA/nYiOxooUP805HHnmgx1HJE7sKFSTapmHSCyfd9OFqUTGeD5K4SVZeJT9MSI4ZEVy/OJHf+TgU1B0zJFPhj08GnXQiuR4XBpptjUwd6VW573mXdE8bk72wG+njEDaW9XCMhIRyBcsBGW1Nio3/jqrNOF8dfoO4DWsLIiHUofYguBLiWBqvp+ArWK1y0L0MTJCZ2pRyI+4wESWi16Rb9tayEMigF01151bRRpmSb7Hh239U8OMxqoEfoOHFyuTNhxp+x69sdgdorrapUh+Q2BWHWSQXPOdtKsA9rzjf9CtwDhfW2rNYEQVuBESVY728s=
  - secure: VVrW5vrkksTzkXtkPJfEHefBbPzfNKh+8Ad6qFa5dBssGAuPTxSwnqgm60jWTkmGAmB29oT+AfZZqgGcCV+zhiUnVhts66mFTGR/5nQ8W6YSxQLg181ukiugk7CxiT3mjSwj766NHXQHPx1JrsUa8e9FVXRj7v0Cuib+TVQB5eMxcBH53v8n8Hk9ZNk1TkBD38uNkRO+GCtLFKy/WBBplBTCtCFepfSMmzEmCmRh/jseEjWgRfCF9UDCUj4mXKA7s66NzK6TejVHV2OrMTUeN2CW5XCzLrfmc+ybQSdoc8u0FEOUADopkM6b/O7LT/eqDnAYZtu34UD5vRY4DF6umRjBKcF8TnuEuqsBlfwCjSWAk4qTDUgahs2vIwjjbll/4fo367LKuCfSckkRyYPMrL0mtYpjvZ66zBaw1ORvbXALxCV7ca6XHtjoEVKHMUoJy9TJW0aFTbSluqmQYrcC8P/gnZIXrc0vFeItHRWTfkNg39PkND2H5PbGAUxo0HVHelO2SAtQotx9NCXj4Dtff3rpuiF1XUupkmiRQh1ob4XKtdVLB6pR/MXIbm3MsWPJwaauCHYBGqeaKb7CPuItDFjFnTZauSf6qxGAE97MluI6LAAZEhQF3g3Nfl+4Ggzz9tmwO5xpXf11tGOT59QRponkmsJSGI2Izi8055YGA3Y=

